name: Test

on: [push]

jobs:
  Test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v2
      with:
        go-version: "1.16"

    - name: Get hclfmt
      run: GO111MODULE=on go get github.com/hashicorp/hcl/v2/cmd/hclfmt

    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Run tests
      run: |
        cd tests && make test

